name: mandrill
version: 1.0.0
description: An unofficial but maintained API client for the Mandrill email as a service product.
environment:
  sdk: ">=1.4.0 <3.0.0"
author:
- Matias Meno <matias.meno@exit.live>
homepage: https://gitlab.com/exitlive/mandrill-dart
documentation: https://mandrillapp.com/api/docs/index.dart.html
dependencies:
  codable: ^1.0.0-beta.2
  meta: ^1.1.6
  http: ^0.11.0
  intl: ^0.15.0
dev_dependencies:
  test: ^1.3.0
  mockito: ^3.0.0
  grinder: ^0.8.3