name: mandrill
version: 1.0.0
description: An unofficial but maintained API client for the Mandrill email as a service product.
environment:
  sdk: ">=1.4.0 <3.0.0"
author:
- Matias Meno <matias.meno@exit.live>
- Mandrill Devs <community@mandrill.com>
homepage: https://gitlab.com/exitlive/mandrill-dart
documentation: https://mandrillapp.com/api/docs/index.dart.html
dev_dependencies:
  test: any
