name: mandrill
version: 2.0.0
description: An unofficial but maintained API client for the Mandrill email as a service product.
environment:
  sdk: '>=2.12.0 <3.0.0'
homepage: https://gitlab.com/exitlive/mandrill-dart
dependencies:
  meta: ^1.7.0
  http: ^0.13.3
  intl: ^0.18.0
  logging: ^1.0.2
  conduit_codable: ^3.0.11
dev_dependencies:
  test: ^1.17.12
  mocktail: ^0.1.4
  grinder: ^0.9.0
  pedantic: ^1.11.1
